### ISSUE TITLE
General Direction of the Project

### ISSUE THREAD

**Issue by ProgrammerE** [rsairu/hello-world#4]
Why is this a fish and chicken rearing AND Python programming project? Should those not be 3 projects?

**Comment by rsairu** [comment]
the fish nitrogenate the water for the gardens in / around the chicken plot. separate plant cultivation such as of hornwort can generate animal feed.

python might be useful to automate various sensors, and programming in general for other technical aspects.

the waterworld file was irrelevant and removed
